---
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: read

jobs:
  quality-assurance:
    name: Quality Assurance
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.24.x]

    steps:
      - uses: actions/checkout@v5.0.0
      - uses: actions/setup-go@v6.0.0
        with:
          go-version: ${{ matrix.go-version }}
      - uses: golangci/golangci-lint-action@v8.0.0
        with:
          version: latest
      - run: go test -race -v ./...
      - run: go vet ./...
      - run: golangci-lint run
