---
name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        id: release
        uses: googleapis/release-please-action@v4.2.0
        with:
          token: ${{ secrets.GH_PAT_RELEASE_PLEASE_ACTION }}
          config-file: .github/.release-please-config.json
          manifest-file: .github/.release-please-manifest.json
